In [1]:
print("hello")

hello


In [29]:
import numpy as np

In [9]:
import numpy as np
arr_1d = np.array([1,2,3])
print(arr_1d)
#2*3 matrix 2d
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)
#3d array
arr_3d=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr_3d)
#4d array
arr_4d=np.array([[[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]],[[[13,24,35],[45,65,67]],[[78,88,90],[100,1761,127]]]])
print(arr_4d)

[1 2 3]
[[1 2 3]
 [4 5 6]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[[   1    2    3]
   [   4    5    6]]

  [[   7    8    9]
   [  10   11   12]]]


 [[[  13   24   35]
   [  45   65   67]]

  [[  78   88   90]
   [ 100 1761  127]]]]


In [11]:
import numpy as np
#zeros
arr_zeros = np.zeros((4,5))
print(arr_zeros)
arr_ones = np.ones((2,3))
print(arr_ones)
#randoms
arr_random= np.random.random((3,3))
print(arr_random)
#identity matrix
identity_arr = np.eye(4)
print(identity_arr)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0.99301656 0.51689403 0.56097656]
 [0.68577346 0.4581572  0.5606765 ]
 [0.89188463 0.02539312 0.19011876]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
import numpy as np
range_arr=np.arange(0,11,2) #arange in a arange
print(range_arr)

[ 0  2  4  6  8 10]


In [15]:
import numpy as np
#attributes of numpy
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print("shape of arr",arr.shape)
print("size of arr",arr.size)
print("dimension of arr",arr.ndim)
print("data type of arr",arr.dtype)


shape of arr (2, 2, 3)
size of arr 12
dimension of arr 3
data type of arr int64


In [25]:
import numpy as np
'''
You are working as a Data Engineer for a smart agriculture startup that collects sensor data from multiple greenhouses.
Each greenhouse has sensors that record temperature (°C) readings at different times of the day.
You received the following data:
Your tasks are:
Create NumPy arrays
Create a 2D NumPy array named temp_data to represent the temperature readings from both greenhouses.
Print the array.
Check array properties
Print the shape, size, data type, and number of dimensions of temp_data.
Add a third greenhouse
The third greenhouse (GH3) records [21, 23, 22].
Create a new array updated_temp_data that includes all three greenhouses.
Generate supporting data
Create a zeros array (2×3) called sensor_error_flags to represent whether there were any sensor errors (0 means no error).
Create an identity matrix of size 3×3 named greenhouse_identity to uniquely identify each greenhouse.
Display all arrays
Print updated_temp_data, sensor_error_flags, and greenhouse_identity.
 '''
temp_data=np.array([[22,25,20],[24,26,23]])
print(temp_data)
print(temp_data.shape)
print(temp_data.size)
print(temp_data.dtype)
print(temp_data.ndim)
updated_temp_data=np.array([[22,25,20],[24,26,23],[21,23,22]])
print(updated_temp_data)
sensor_error_flags = np.zeros((2,3))
print(sensor_error_flags)
greenhouse_identity=np.eye(3)
print(greenhouse_identity)

[[22 25 20]
 [24 26 23]]
(2, 3)
6
int64
2
[ 1  2  3  4  5  6  7  8  9 10 11 12 21 23 22]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [28]:
#indexing
arr=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr[1][1])
print(arr[1][0])

[[1 2 3]
 [4 5 6]]
5
4


In [32]:
#slicing
arr=np.array([[1,2,3],[4,5,6]])
print(arr[0:1,1:2])
print(arr[0:2,0:2])
print(arr[0:2,0:3])

[[2]]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


Indexing and Slicing:
You are working as a Data Analyst at a fruit distribution company.
The company stores the number of fruit boxes shipped per day (for 1 week) in a 2D NumPy array where:
Each row represents a type of fruit.
Each column represents a day of the week (Mon–Sun).


Your Tasks
Create the 2D NumPy array
Create an array named shipments using the above data.
Access single elements (Indexing):
Get the number of Apples shipped on Wednesday.
Get the number of Oranges shipped on Sunday.
Access multiple elements (Slicing):
Extract all the weekday shipments (Mon–Fri) for all fruits.
Extract only the weekend shipments (Sat & Sun).
Extract the shipments of Apples from Wednesday to Saturday.
Bonus (Practice thinking):
Replace the Saturday shipment of Apples (currently 80) with 100 using indexing
            [mon,tue,web,thu,fri,sat,sun]
  apples    ..........................
  oranges   ...........................

In [35]:
import numpy as np
shipments = np.array([[50,60,55,70,65,80,90],[40,45,50,60,55,70,75]])
print("apples shipped on wednesday",shipments[0][2])
print("oranges shipped on sunday",shipments[1][6])
print("friuts from monday to friday",shipments[: ,0:5])
print("friuts from weekends",shipments[:,5:7])
print("apples from wednesday to saturday",shipments[ : 1,2:6])
shipments[0][5]=100
print("after saturday apples to 100",shipments)

apples shipped on wednesday 55
oranges shipped on sunday 75
friuts from monday to friday [[50 60 55 70 65]
 [40 45 50 60 55]]
friuts from weekends [[80 90]
 [70 75]]
apples from wednesday to saturday [[55 70 65 80]]
after saturday apples to 100 [[ 50  60  55  70  65 100  90]
 [ 40  45  50  60  55  70  75]]


In [39]:
#arithemetic operations on arrays
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])
print(a+b)
print(a*b)
print(a*2)
#matrix operations
mat1=np.array([[1,2],[3,4]])
mat2=np.array([[5,6],[7,8]])
res = np.dot(mat1,mat2)
print(res)
print(mat1*mat2)

[ 6  8 10 12]
[ 5 12 21 32]
[2 4 6 8]
[[19 22]
 [43 50]]
[[ 5 12]
 [21 32]]


In [42]:
#broadcasting
import numpy as np
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([1,2,3])
print(a+b)


[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [51]:
#universal functions
a=np.array([1,2,3,4,5,6,7,8,90,10])
print("exponents",np.round(np.exp(a)))
print("log",np.round(np.log(a)))
print("square root",np.floor(np.sqrt(a)))
print("sin",np.ceil(np.sin(a)))
print("cos",np.trunc(np.cos(a)))
print("tan",np.arctan(a))

exponents [3.00000000e+00 7.00000000e+00 2.00000000e+01 5.50000000e+01
 1.48000000e+02 4.03000000e+02 1.09700000e+03 2.98100000e+03
 1.22040329e+39 2.20260000e+04]
log [0. 1. 1. 1. 2. 2. 2. 2. 4. 2.]
square root [1. 1. 1. 2. 2. 2. 2. 2. 9. 3.]
sin [ 1.  1.  1. -0. -0. -0.  1.  1.  1. -0.]
cos [ 0. -0. -0. -0.  0.  0.  0. -0. -0. -0.]
tan [0.78539816 1.10714872 1.24904577 1.32581766 1.37340077 1.40564765
 1.42889927 1.44644133 1.55968567 1.47112767]


In [57]:
#aggregate functions
print("sum",np.sum(a))
print("min",np.min(a))
print("max",np.max(a))
print("mean",np.mean(a))
print("median",np.median(a))
print("variance",np.var(a))
print("standard deviation",np.std(a))


sum 136
min 1
max 90
mean 13.6
median 5.5
variance 655.44
standard deviation 25.601562452319197


You are a data engineer at a renewable-energy company that runs 3 solar farms.

Each farm has 4 solar panels, and each panel reports hourly energy production (kWh) for 3 hours during a test window.

Given data (raw)
Create arrays from these values:
production — shape (3 farms × 4 panels × 3 hours) represented as a 2D array per farm (you can stack/create as shown in tasks).
Farm A panels (rows = panels, cols = hours):


Tasks
Create arrays
Create three 2D NumPy arrays farmA, farmB, farmC (each shape (4,3)).
Stack them into a single 3D array production_all of shape (3, 4, 3).
Array attributes
Print the .shape, .size, .dtype, and .ndim of production_all.
Per-farm totals (arithmetic & aggregation)
Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
Compute mean, std, and var per farm.
Per-hour matrix multiplication idea (matrix op)
For a quick weighted estimate, create a hour_weights row vector of shape (3,) = [0.5, 1.0, 0.75] (weights for hour1, hour2, hour3).
Compute weighted_per_panel by performing a dot product between each farm's panel-row and hour_weights to get per-panel weighted energy. (Use np.dot / matrix multiplication appropriately.)
Broadcasting adjustments
The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually).
Element-wise arithmetic (ufuncs: add/sub/mul/div/power/mod)
Compute a normalized version where you:
subtract the per-farm mean (use broadcasting),
divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
Apply many ufuncs (use the ufuncs listed previously)

Apply the following element-wise operations (create variables for each) on the normalized data (or a copy) and show the resulting arrays (or summaries — shape/dtype/first row) where appropriate:
Exponential family: np.exp, np.expm1, np.log (note: handle non-positive inputs if needed), np.log10, np.log2.
Trigonometric: np.sin, np.cos, np.tan, np.arcsin, np.arccos, np.arctan, plus np.degrees, np.radians applied appropriately.
Rounding: np.round, np.floor, np.ceil, np.trunc.
Comparison & logical ufuncs: create a boolean mask high_output = production_all > 20 and apply np.logical_and, np.logical_or, np.logical_not, np.logical_xor combining masks (e.g., high_output and even_hours_mask). Also use comparison ufuncs like np.greater_equal, np.less.
Bitwise ufuncs (on integer arrays): create an integer array alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]]) for each farm (shape match required) — then apply np.bitwise_and, np.bitwise_or, np.invert where sensible.
Arithmetic ufuncs again: np.add, np.subtract, np.multiply, np.divide, np.power, np.mod.
Aggregations over ufunc outputs: e.g., np.sum(np.exp(...)), np.mean(np.sin(...)).
Broadcast-based summary table
Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel), and then compute a (3,) boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all.
Final KPIs (aggregation)
Compute:
overall_total (sum of all farms),
peak_hour value (max across hours) and which farm & panel produced it (use np.argmax with careful unraveling),
average_per_panel across all farms.



In [76]:
import numpy as np
a=np.array([[10,12,11],
            [9,11,10],
            [12,13,14],
            [8,7,9]])
b=np.array([[20,19,21],
            [18,20,19],
            [22,23,21],
            [17,18,16]])
c=np.array([[15,16,14],
            [14,13,15],
            [16,17,18],
            [12,11,13]])
production_all=np.array([a,b,c], dtype=float)
print(production_all.shape)
print(production_all.size)
print(production_all.dtype)
print(production_all.ndim)
print("sum for farm1",np.sum(production_all[0]))
print("sum for farm2",np.sum(production_all[1]))
print("sum for farm3",np.sum(production_all[2]))
print("mean for farm1",np.mean(production_all[0]))
print("mean for farm2",np.mean(production_all[1]))
print("mean for farm3",np.mean(production_all[2]))
print("std for farm1",np.std(production_all[0]))
print("std for farm2",np.std(production_all[1]))
print("std for farm3",np.std(production_all[2]))
print("var for farm1",np.var(production_all[0]))
print("var for farm2",np.var(production_all[1]))
print("var for farm3",np.var(production_all[2]))
#
hours_weights=np.array([0.5,1.0,0.75])
weighted_per_panel=np.dot(production_all,hours_weights)
print(weighted_per_panel)


production_all[1 :2]+=0.5
print(production_all)
per_farm_mean = np.mean(production_all,axis=(1,2))
per_farm_std = np.std(production_all, axis=(1, 2))
normalized_farm = production_all-per_farm_mean
print(normalized_farm)
normalized_farm=normalized_farm/per_farm_std
print(normalized_farm)
print(np.exp(np.round(normalized_farm)+1))
print(np.expm1(normalized_farm))
print(np.log(np.round(normalized_farm)+1))
print(np.log10(np.round(normalized_farm)+1))
print(np.log2(np.round(normalized_farm)+1))
print(np.degrees(np.sin(normalized_farm)))
print(np.radians(np.sin(normalized_farm)))
print(np.degrees(np.cos(normalized_farm)))
print(np.radians(np.cos(normalized_farm)))
print(np.degrees(np.tan(normalized_farm)))
print(np.radians(np.tan(normalized_farm)))
print(np.degrees(np.arcsin(normalized_farm)))
print(np.degrees(np.arccos(normalized_farm)))
print(np.degrees(np.arctan(normalized_farm)))
print(np.round(normalized_farm))
print(np.floor(normalized_farm))
print(np.ceil(normalized_farm))
print(np.trunc(normalized_farm))

print(np.logical_and(np.greater_equal(normalized_farm,20),production_all%2==0))
print(np.logical_or(production_all>20,production_all%2==0))
print(np.logical_xor(production_all>20,production_all%2==0))


(3, 4, 3)
36
float64
3
sum for farm1 126.0
sum for farm2 234.0
sum for farm3 174.0
mean for farm1 10.5
mean for farm2 19.5
mean for farm3 14.5
std for farm1 1.9790570145063195
std for farm2 1.9790570145063195
std for farm3 1.9790570145063195
var for farm1 3.9166666666666665
var for farm2 3.9166666666666665
var for farm3 3.9166666666666665
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
[[[10.  12.  11. ]
  [ 9.  11.  10. ]
  [12.  13.  14. ]
  [ 8.   7.   9. ]]

 [[20.5 19.5 21.5]
  [18.5 20.5 19.5]
  [22.5 23.5 21.5]
  [17.5 18.5 16.5]]

 [[15.  16.  14. ]
  [14.  13.  15. ]
  [16.  17.  18. ]
  [12.  11.  13. ]]]
[[[ -0.5  -8.   -3.5]
  [ -1.5  -9.   -4.5]
  [  1.5  -7.   -0.5]
  [ -2.5 -13.   -5.5]]

 [[ 10.   -0.5   7. ]
  [  8.    0.5   5. ]
  [ 12.    3.5   7. ]
  [  7.   -1.5   2. ]]

 [[  4.5  -4.   -0.5]
  [  3.5  -7.    0.5]
  [  5.5  -3.    3.5]
  [  1.5  -9.   -1.5]]]
[[[-0.25264558 -4.04232922 -1.76851903]
  [-0.75793673 -4.54762037 -2.273

/tmp/ipython-input-3686620300.py:47: RuntimeWarning: divide by zero encountered in log
  print(np.log(np.round(normalized_farm)+1))
/tmp/ipython-input-3686620300.py:47: RuntimeWarning: invalid value encountered in log
  print(np.log(np.round(normalized_farm)+1))
/tmp/ipython-input-3686620300.py:48: RuntimeWarning: divide by zero encountered in log10
  print(np.log10(np.round(normalized_farm)+1))
/tmp/ipython-input-3686620300.py:48: RuntimeWarning: invalid value encountered in log10
  print(np.log10(np.round(normalized_farm)+1))
/tmp/ipython-input-3686620300.py:49: RuntimeWarning: divide by zero encountered in log2
  print(np.log2(np.round(normalized_farm)+1))
/tmp/ipython-input-3686620300.py:49: RuntimeWarning: invalid value encountered in log2
  print(np.log2(np.round(normalized_farm)+1))
/tmp/ipython-input-3686620300.py:56: RuntimeWarning: invalid value encountered in arcsin
  print(np.degrees(np.arcsin(normalized_farm)))
/tmp/ipython-input-3686620300.py:57: RuntimeWarning: invalid v

In [90]:
alerts = np.array([[1,0,1],[0,0,1],[1,1,0],[0,1,0]])
print(np.bitwise_and(alerts,production_all[0].astype(int)))
print(np.bitwise_or(alerts,production_all[0].astype(int)))
print(np.invert(alerts,production_all[0].astype(int)))
print(np.add(production_all,2))
print(np.multiply(production_all,2))
print(np.divide(production_all,2))
print(np.power(production_all,2))
print(np.mod(production_all,2))
#aggregate
print(np.sum(np.exp(production_all)))


[[0 0 1]
 [0 0 0]
 [0 1 0]
 [0 1 0]]
[[11 12 11]
 [ 9 11 11]
 [13 13 14]
 [ 8  7  9]]
[[-2 -1 -2]
 [-1 -1 -2]
 [-2 -2 -1]
 [-1 -2 -1]]
[[[12.  14.  13. ]
  [11.  13.  12. ]
  [14.  15.  16. ]
  [10.   9.  11. ]]

 [[22.5 21.5 23.5]
  [20.5 22.5 21.5]
  [24.5 25.5 23.5]
  [19.5 20.5 18.5]]

 [[17.  18.  16. ]
  [16.  15.  17. ]
  [18.  19.  20. ]
  [14.  13.  15. ]]]
[[[20. 24. 22.]
  [18. 22. 20.]
  [24. 26. 28.]
  [16. 14. 18.]]

 [[41. 39. 43.]
  [37. 41. 39.]
  [45. 47. 43.]
  [35. 37. 33.]]

 [[30. 32. 28.]
  [28. 26. 30.]
  [32. 34. 36.]
  [24. 22. 26.]]]
[[[ 5.    6.    5.5 ]
  [ 4.5   5.5   5.  ]
  [ 6.    6.5   7.  ]
  [ 4.    3.5   4.5 ]]

 [[10.25  9.75 10.75]
  [ 9.25 10.25  9.75]
  [11.25 11.75 10.75]
  [ 8.75  9.25  8.25]]

 [[ 7.5   8.    7.  ]
  [ 7.    6.5   7.5 ]
  [ 8.    8.5   9.  ]
  [ 6.    5.5   6.5 ]]]
[[[100.   144.   121.  ]
  [ 81.   121.   100.  ]
  [144.   169.   196.  ]
  [ 64.    49.    81.  ]]

 [[420.25 380.25 462.25]
  [342.25 420.25 380.25]
  [506.25 5

In [87]:
#reshaping
arr = np.array([1,2,3,4,5,6])
reshaped=arr.reshape(3,2)
print(reshaped)

[[1 2]
 [3 4]
 [5 6]]


In [89]:
#stacking and splitting
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
arr = np.array([1,2,3,4,5,6,7,8])
print(np.array_split(arr,3))

[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8])]


In [91]:
#boolean index
arr = np.array([1,2,3,4,5,6,7,8,])
print(arr[arr>3])
#facy index
print(arr[[0,2]])

[4 5 6 7 8]
[1 3]


In [97]:
#copy and view
arr = np.array([1,2,3])
copy = arr.copy()
copy[0]=100
print(arr)
views = arr.view()
views[1]=20
print(views)



[1 2 3]
[ 1 20  3]


In [99]:
#save and load
arr=np.array([1,2,3])
np.save('array.npy',arr)
loaded_arr = np.load('array.npy')
print(loaded_arr)

[1 2 3]


Create a 1D array of numbers from 10 to 50.
Create a 3x3 array of random numbers between 0 and 1.
Array Attributes
Find the shape, size, and data type of the array you created in the previous task.
Basic Operations
Add 5 to every element of a 1D array.
Multiply two 2D arrays element-wise.
Indexing and Slicing
Create a 5x5 array of integers from 1 to 25. Extract:
The first row.
The last column.
A subarray of the first three rows and first two columns.
Aggregation
Create a 10-element array of random integers between 10 and 100. Find:
The maximum value.
The minimum value.
The mean and standard deviation.
Reshaping
Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
Broadcasting
Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
Filtering
Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
Matrix Multiplication
Create two 2x2 matrices and perform matrix multiplication.
Advanced Indexing
Given a 4x4 array, use fancy indexing to extract the diagonal elements.

In [131]:
arr=np.arange(10,51)
ra= np.random.randint(0, 2, size=(3,3))
ra2=np.random.randint(0, 2, size=(3,3))

print(ra.shape)
print(ra.size)
print(ra.dtype)
print(ra+5)
print(np.dot(ra,ra2))
arr2 = np.arange(1,26).reshape(5,5)
print(arr2[0])
print(arr2[:,4])
print(arr2[:3,:2])


(3, 3)
9
int64
[[6 5 5]
 [6 6 5]
 [6 5 6]]
[[0 1 0]
 [1 2 0]
 [1 1 1]]
[1 2 3 4 5]
[ 5 10 15 20 25]
[[ 1  2]
 [ 6  7]
 [11 12]]


In [129]:
arr = np.random.randint(10,100,size=(1,10))
print(np.max(arr))
print(np.min(arr))
print(np.std(arr))
print(np.var(arr))
arr2 = np.arange(1,13)
print(arr2)
arr2 =arr2.reshape(3,4)
print(arr2)

94
16
26.858890520645115
721.4
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [132]:
one=np.ones((3,3))
one =one +[1,2,3]
print(one)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [149]:
arr = np.random.randint(1,50,size=(1,10))
print(arr[arr%5==0])
m1 = np.array([[1,2],[3,4]])
m2 = np.array([[5,6],[7,8]])
print(np.dot(m1,m2))

[40]
[[19 22]
 [43 50]]


In [144]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
print(arr[[0,1,2,3],[0,1,2,3]])

[ 1  6 11 16]
